### ISSUE TITLE
是否是基于casa的“一种基于ResponderChain的对象交互方式”这篇博客的方案？

### ISSUE THREAD

**Issue by leung-c** [GodL/ResponderChain#1]
博客地址：[一种基于ResponderChain的对象交互方式](https://casatwy.com/responder_chain_communication.html)

**Comment by GodL** [comment]
这种传递事件的方式很久之前就存在了，这个仓库只是提供了一个swift的实现

**Comment by xiaosao6** [comment]
请问下ResponderValue这个结构为什么这样设计呢？
直接用 let _value: Any 行吗

**Comment by GodL** [comment]
> 请问下ResponderValue这个结构为什么这样设计呢？
> 直接用 let _value: Any 行吗

这个结构是一个类型擦除的实现，使用Any倒也没什么问题
